apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
  labels:
    app: app-three
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
        - name: custom-container
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: MESSAGE
              value: "Hello from app-three."
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
  namespace: app-three-namespace
spec:
  selector:
    app: app-three
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
