server_ip = "192.168.56.110"

Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine312"

    config.vm.provider "virtualbox" do |v|
        v.memory    = "1024"
        v.cpus      = "1"
    end

    config.vm.synced_folder "./confs", "/vagrant/confs"
    config.vm.synced_folder "./scripts", "/vagrant/scripts"

    config.vm.define "juan-gons" do |node|
        node.vm.hostname = "juan-gons"
        node.vm.network "private_network", ip: "192.168.56.110"
        node.vm.provision "shell", path: "./scripts/install-server.sh", args: [server_ip]
    end
end