server_ip = "192.168.56.110"

agent_ip = "192.168.56.111"


Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine312"
  
	config.vm.provider "virtualbox" do |v|
	  v.memory = "1024"
	  v.cpus = "1"
	end
  
	# Sincronizar las carpetas 'config' y 'scripts' con todas las VMs
	config.vm.synced_folder "./confs", "/vagrant/confs"
	config.vm.synced_folder "./scripts", "/vagrant/scripts"
  
	config.vm.define "controller" do |node|
	  node.vm.hostname = "controller"
	  node.vm.network "private_network", ip: "192.168.56.110"
	  node.vm.provision "shell", path: "./scripts/install-controller.sh", args: [server_ip]
	end
  
	config.vm.define "agent" do |node|
	  node.vm.hostname = "agent"
	  node.vm.network "private_network", ip: "192.168.56.111"
	  node.vm.provision "shell", path: "./scripts/install-agent.sh", args: [server_ip]
	end
end