apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: custom-container
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: MESSAGE
              value: "Hello from app-two."
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
  namespace: app-two-namespace
spec:
  selector:
    app: app-two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
