Vagrant.configure("2") do |config|
    config.vm.box = "gutehall/debian12"

    config.vm.provider "virtualbox" do |v|
        v.memory    = "1024"
        v.cpus      = "1"
    end

    config.vm.define "juan-gonS" do |node|
        node.vm.hostname = "juan-gonS"
        node.vm.network "private_network", ip: "192.168.56.115"
    end
end